# Site settings
title: The Back of the Envelope
email: pillsbury+blog[at]gmail[dot]com
description: > # this means to ignore newlines until "baseurl:"
  Blather of dubious value.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pillsy.github.io" # the base hostname & protocol for your site
# twitter_username: DucksForDuckGod
github_username:  pillsy

# Build settings
markdown: kramdown
